//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVITIES()
        {
            this.LIST = new HashSet<LIST>();
        }
    
        public int act_id { get; set; }
        public Nullable<System.DateTime> act_date { get; set; }
        public Nullable<int> sved_id { get; set; }
        public Nullable<int> dol_id { get; set; }
        public Nullable<int> act_code { get; set; }
        public Nullable<int> prich_id { get; set; }
        public Nullable<int> osn_id { get; set; }
        public Nullable<System.DateTime> act_from { get; set; }
        public Nullable<System.DateTime> act_to { get; set; }
        public string act_cancel { get; set; }
    
        public virtual DOLJNOSTI DOLJNOSTI { get; set; }
        public virtual OSNOVANIYA OSNOVANIYA { get; set; }
        public virtual PRICHINI_YVOLNENIYA PRICHINI_YVOLNENIYA { get; set; }
        public virtual SVEDENIYA SVEDENIYA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIST> LIST { get; set; }
    }
}
