//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIST
    {
        public int list_id { get; set; }
        public Nullable<int> act_id { get; set; }
        public Nullable<int> std_id { get; set; }
    
        public virtual ACTIVITIES ACTIVITIES { get; set; }
        public virtual STD_R STD_R { get; set; }
    }
}
