//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ekz_lysanovEntities : DbContext
    {
        public ekz_lysanovEntities()
            : base("name=ekz_lysanovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVITIES> ACTIVITIES { get; set; }
        public virtual DbSet<DOLJNOSTI> DOLJNOSTI { get; set; }
        public virtual DbSet<LIST> LIST { get; set; }
        public virtual DbSet<OSNOVANIYA> OSNOVANIYA { get; set; }
        public virtual DbSet<PODRAZDELENIYA> PODRAZDELENIYA { get; set; }
        public virtual DbSet<PRICHINI_YVOLNENIYA> PRICHINI_YVOLNENIYA { get; set; }
        public virtual DbSet<RABOTNIKI> RABOTNIKI { get; set; }
        public virtual DbSet<RABOTODATELI> RABOTODATELI { get; set; }
        public virtual DbSet<STD_R> STD_R { get; set; }
        public virtual DbSet<SVEDENIYA> SVEDENIYA { get; set; }
    }
}
