//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICHINI_YVOLNENIYA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRICHINI_YVOLNENIYA()
        {
            this.ACTIVITIES = new HashSet<ACTIVITIES>();
        }
    
        public int prich_id { get; set; }
        public string prich_type { get; set; }
        public string prich_document { get; set; }
        public Nullable<int> prich_state { get; set; }
        public Nullable<int> prich_part { get; set; }
        public Nullable<int> prich_point { get; set; }
        public Nullable<int> prich_subpoint { get; set; }
        public Nullable<int> prich_abzac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVITIES> ACTIVITIES { get; set; }
    }
}
