//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RABOTNIKI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RABOTNIKI()
        {
            this.STD_R = new HashSet<STD_R>();
        }
    
        public int rab_id { get; set; }
        public string rab_fio { get; set; }
        public Nullable<System.DateTime> rab_bdate { get; set; }
        public string rab_snils { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STD_R> STD_R { get; set; }
    }
}
