//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class STD_R
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STD_R()
        {
            this.LIST = new HashSet<LIST>();
        }
    
        public int std_id { get; set; }
        public Nullable<int> rab_id { get; set; }
        public Nullable<int> dat_id { get; set; }
        public Nullable<System.DateTime> std_date { get; set; }
        public string std_ryk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIST> LIST { get; set; }
        public virtual RABOTNIKI RABOTNIKI { get; set; }
        public virtual RABOTODATELI RABOTODATELI { get; set; }
    }
}
